### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by alexandre-mbm** [pavelkomarov/hyde#1]
Do you have them?
Share some URL please.

**Comment by pavelkomarov** [comment]
How I made the discoveries that allowed me to create an operational example is detailed [here](https://stackoverflow.com/questions/57895117/how-to-use-theme-from-github-io-site-for-github-project-pages-sites). I think the full thought process is easier to follow and that the extra insights and gotchas are worth knowing.

If you just want to jump straight to a couple fairly minimal examples, see my `.io` repo and `big-holes-in-big-data`.

Hope that helps. Never expected an issue on this repo. How'd you find me?

**Comment by alexandre-mbm** [comment]
I was searching about the ``remote_theme`` config. But I am learning with my [web](/alexandre-mbm/web) repo now, and with [this](https://matthiaslischka.at/2018/12/03/github-jekyll-best-practice/).

Also with the [Liquid's Documentation](https://shopify.github.io/liquid/).

**Comment by pavelkomarov** [comment]
Is your problem solved?

**Comment by alexandre-mbm** [comment]
I will still return to the topic of study for my particular requirements. I have learned a few things; I have made it work but there are dissatisfactions. Feel free to close the issue at your repository.
